# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CarbonGuardianAngel < Formula
  desc "The Identity and Excellence Guardian for Nexo-Fortis AI agents."
  homepage "https://github.com/fortissolucoescontato-bit/carbon-guardian-angel"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortissolucoescontato-bit/carbon-guardian-angel/releases/download/v0.1.0/carbon-guardian-angel_0.1.0_darwin_amd64.tar.gz"
      sha256 "b06f4a8bd6603072e69d72a4361b90a7d098a6575bdc8b946ed68ae2533bc0e7"

      define_method(:install) do
        bin.install "carbon-guardian-angel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortissolucoescontato-bit/carbon-guardian-angel/releases/download/v0.1.0/carbon-guardian-angel_0.1.0_darwin_arm64.tar.gz"
      sha256 "5d796e1877c1cca84352595454648718b565a0811199dae0134e54fcf389a872"

      define_method(:install) do
        bin.install "carbon-guardian-angel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortissolucoescontato-bit/carbon-guardian-angel/releases/download/v0.1.0/carbon-guardian-angel_0.1.0_linux_amd64.tar.gz"
      sha256 "1764ba7e123de67d08f24ce64537e3d9b0412e69f043906b85cad2ebec8c6cfa"
      define_method(:install) do
        bin.install "carbon-guardian-angel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortissolucoescontato-bit/carbon-guardian-angel/releases/download/v0.1.0/carbon-guardian-angel_0.1.0_linux_arm64.tar.gz"
      sha256 "0f5ed0a8a3e04fb7bce01b8e80b78c8bae359b78e1eea2d404aba890ec212a9b"
      define_method(:install) do
        bin.install "carbon-guardian-angel"
      end
    end
  end
end
