# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KortexEngram < Formula
  desc "Persistent memory for AI coding agents. Agent-agnostic, single binary, zero dependencies."
  homepage "https://github.com/fortissolucoescontato-bit/kortex-engram"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortissolucoescontato-bit/kortex-engram/releases/download/v0.1.0/kortex-engram_0.1.0_darwin_amd64.tar.gz"
      sha256 "04ce4906d8cdb838af3da9f710edc84bfabc609b7edc5126d7b77fb40365e2ca"

      define_method(:install) do
        bin.install "kortex-engram"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortissolucoescontato-bit/kortex-engram/releases/download/v0.1.0/kortex-engram_0.1.0_darwin_arm64.tar.gz"
      sha256 "7569dda9d81a9dc89b7b8d5085c05529068e67ea94529ecc3cb7e0fbbe7e9738"

      define_method(:install) do
        bin.install "kortex-engram"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortissolucoescontato-bit/kortex-engram/releases/download/v0.1.0/kortex-engram_0.1.0_linux_amd64.tar.gz"
      sha256 "6d0f9841dbb16a475dc5fff126e8149cac3d4732396b5d90f923458d829d7bac"
      define_method(:install) do
        bin.install "kortex-engram"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortissolucoescontato-bit/kortex-engram/releases/download/v0.1.0/kortex-engram_0.1.0_linux_arm64.tar.gz"
      sha256 "dbe71889bdaf2790af555be7ecf218caf08b8af91a7ea0e2634204e738b0fbae"
      define_method(:install) do
        bin.install "kortex-engram"
      end
    end
  end
end
