# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KortexEngram < Formula
  desc "Persistent memory for AI coding agents. Agent-agnostic, single binary, zero dependencies."
  homepage "https://github.com/fortissolucoescontato-bit/kortex-engram"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortissolucoescontato-bit/kortex-engram/releases/download/v0.1.1/kortex-engram_0.1.1_darwin_amd64.tar.gz"
      sha256 "75dfd2537beef2ea83b78313716bbd7c4f5c26e7a03ada92e80149b264f3745f"

      define_method(:install) do
        bin.install "kortex-engram"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortissolucoescontato-bit/kortex-engram/releases/download/v0.1.1/kortex-engram_0.1.1_darwin_arm64.tar.gz"
      sha256 "81ee77a8862e598806ef79bb873933325ac30d7299e8fb123669e4ff82f675a9"

      define_method(:install) do
        bin.install "kortex-engram"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortissolucoescontato-bit/kortex-engram/releases/download/v0.1.1/kortex-engram_0.1.1_linux_amd64.tar.gz"
      sha256 "699cc413ffa176d2ab1e505935b6870038cb5da01426084d42e191d92f01b749"
      define_method(:install) do
        bin.install "kortex-engram"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortissolucoescontato-bit/kortex-engram/releases/download/v0.1.1/kortex-engram_0.1.1_linux_arm64.tar.gz"
      sha256 "63f73dbf89a4e8f115004bcf4b0a11e8ebde120c03daa54bb8695b2dad9c61f6"
      define_method(:install) do
        bin.install "kortex-engram"
      end
    end
  end
end
