# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kortex < Formula
  desc "Kortex Stack — One command to configure any AI coding agent on any OS."
  homepage "https://github.com/fortissolucoescontato-bit/kortex"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortissolucoescontato-bit/kortex/releases/download/v0.1.0/kortex_0.1.0_darwin_amd64.tar.gz"
      sha256 "3d9f2b49a6d9d9dc33c9b7722e5353f53c11ae08affafabba5f7ae8ef5ab76c3"

      define_method(:install) do
        bin.install "kortex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortissolucoescontato-bit/kortex/releases/download/v0.1.0/kortex_0.1.0_darwin_arm64.tar.gz"
      sha256 "af3a14d55ea0626387d01c9b24b8cf994219e4805c7f32049b8718bdf846a833"

      define_method(:install) do
        bin.install "kortex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortissolucoescontato-bit/kortex/releases/download/v0.1.0/kortex_0.1.0_linux_amd64.tar.gz"
      sha256 "f969e6008c08f2dd19c1c394b754cea319963d411235eeb8c8e1c57051edac98"
      define_method(:install) do
        bin.install "kortex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortissolucoescontato-bit/kortex/releases/download/v0.1.0/kortex_0.1.0_linux_arm64.tar.gz"
      sha256 "f905bf23ca85325d1a031307c841135d1d48b5dddf7891cac9414acafef9d930"
      define_method(:install) do
        bin.install "kortex"
      end
    end
  end
end
